import Header from "@/components/Header";
import "./globals.css";
import Providers from "@/components/Providers";
import NavBar from "@/components/NavBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* Header */}
          <Header />

          {/* navBar */}
          <NavBar />
          {/* searchBox */}

          {children}
        </Providers>
      </body>
    </html>
  );
}
